"""
Renders a self-contained Python script — no imports back into this repo, no
AWS credentials, no network access — that replays one candidate permission's
historical events through the local IAM policy evaluator and prints the
per-event verdicts as JSON. This is the exact script handed to the TrueForge
sandbox's `exec` tool.
"""
from __future__ import annotations

import json

from blast_radius.model import CandidatePermission, HistoricalEvent
from blast_radius.simulator import role_statements_to_plain


def _event_to_json(e: HistoricalEvent) -> dict:
    return {"event_time": e.event_time.isoformat(), "action": e.action, "resource_arns": e.resource_arns}


SANDBOX_SCRIPT_TEMPLATE = r'''
# Blast Radius sandbox replay script — generated by blast_radius/sandbox_code.py.
# Runs entirely inside the TrueForge sandbox. No network access, no AWS
# credentials of any kind. Reimplements IAM policy evaluation from scratch
# (does not call any AWS API) and prints RESULT_JSON on stdout.
import json
import re

CANDIDATE_ACTION = %(candidate_action_json)s
ROLE_STATEMENTS = %(statements_json)s
EVENTS = %(events_json)s


def _wildcard_match(pattern, value):
    regex = re.escape(pattern).replace(r"\*", ".*").replace(r"\?", ".")
    return re.fullmatch(regex, value) is not None


def _matches_any(patterns, value):
    return any(_wildcard_match(p, value) for p in patterns)


def statement_applies_to_action(stmt, action):
    if stmt["actions"]:
        return _matches_any(stmt["actions"], action)
    if stmt["not_actions"]:
        return not _matches_any(stmt["not_actions"], action)
    return False


def statement_applies_to_resource(stmt, resource_arns):
    if not resource_arns:
        return "*" in stmt["resources"]
    if stmt["resources"]:
        return all(_matches_any(stmt["resources"], r) for r in resource_arns)
    if stmt["not_resources"]:
        return all(not _matches_any(stmt["not_resources"], r) for r in resource_arns)
    return False


def evaluate(statements, action, resource_arns):
    decision = "deny"
    for stmt in statements:
        if stmt["has_condition"]:
            continue
        if not statement_applies_to_action(stmt, action):
            continue
        if not statement_applies_to_resource(stmt, resource_arns):
            continue
        if stmt["effect"] == "Deny":
            return "deny"
        if stmt["effect"] == "Allow":
            decision = "allow"
    return decision


def remove_action(statements, action_to_remove):
    out = []
    for stmt in statements:
        if stmt["effect"] == "Allow" and action_to_remove in stmt["actions"]:
            remaining = [a for a in stmt["actions"] if a != action_to_remove]
            if remaining:
                out.append({**stmt, "actions": remaining})
        else:
            out.append(stmt)
    return out


hypothetical = remove_action(ROLE_STATEMENTS, CANDIDATE_ACTION)
results = []
for i, event in enumerate(EVENTS):
    if event["action"] != CANDIDATE_ACTION:
        continue
    verdict = evaluate(hypothetical, event["action"], event["resource_arns"])
    results.append({"event_index": i, "local_verdict": verdict})

print("STATUS: OK")
print("RESULT_JSON:" + json.dumps({"candidate_action": CANDIDATE_ACTION, "verdicts": results}))
'''


def render_sandbox_script(candidate: CandidatePermission, all_role_statements, events: list[HistoricalEvent]) -> str:
    return SANDBOX_SCRIPT_TEMPLATE % {
        "candidate_action_json": json.dumps(candidate.action),
        "statements_json": json.dumps(role_statements_to_plain(all_role_statements)),
        "events_json": json.dumps([_event_to_json(e) for e in events]),
    }
